# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033bf7adb04556528c841a6affbf0a7ecc18957df66c3c3a6358e4a3b2a1ccfe1b38f55b75a7b6e3b210eab2d16cc46266340c78e75806006269330614a8bcc2

test:
  secret_key_base: b4badfee181d4aa82c2b43b1162be6ee827057d7059016ded5c8bb69209615886df36df9522e2ed83d5fdc48140e4b7fe3459ea0c2b3ca42b9360e73d762c335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
